extern vec3 up;
extern vec3 dir;
extern vec3 rightV;
extern vec3 moveV;
extern float speed;
extern int firstMouse;
extern float lastX;
extern float lastY;
extern float yaw;
extern float pitch;
int forward;
int left;
int right;
int backward;
int jump;
int crouch;
